version: '3.9'

services:
  logging-accumulator-fluentd:
    image: ctsteele/fluentd-es:latest
    ports:
      - 24224:24224
      - 24224:24224/udp
    environment:
      - FLUENTD_ES_USERNAME=${FLUENTD_ES_USERNAME}
      - FLUENTD_ES_PASSWORD=${FLUENTD_ES_PASSWORD}
    networks:
      reverse-proxy:
      elastic:
    # healthcheck:
    #   test: curl --fail http://localhost:24224 || exit 1
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    # # deploy:
    # #   replicas: ${FLUENTD_INSTANCES}
    # #   resources:
    # #     limits:
    # #       memory: ${FLUENTD_MEMORY_LIMIT}
    # #     reservations:
    # #       memory: ${FLUENTD_MEMORY_RESERVE}
    # # configs:
    # #   - target: /fluentd/etc/fluent.conf
    # #     source: ${FLUENTD_YML_CONFIG}

networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  elastic:
    name: elastic_public
    external: true
  default:
